FROM python:3.11-slim

WORKDIR /app

COPY dockerfiles/requirements-producer.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY producer/ ./producer/

CMD ["python", "producer/kafka_producer.py"]
